toolkit: add CSAF type and helper methods
quay/claircore pull request #1236
Opened 2024-02-02 21:45 UTC by crozzy

Adding the ability to reason with CSAF data and some methods to trawl through the objects.

2024-02-06 21:32 UTC, hdonnay requested changes
I have some questions, suggestions.

2024-02-06 21:32 UTC, hdonnay commented on toolkit/types/csaf/csaf.go
Some of the types for unmarshaling have `omitempty` and some don't: what's the rule of thumb?

2024-02-06 21:32 UTC, hdonnay commented on toolkit/types/csaf/csaf.go
All the recursive walks special-case a slice with no elements. I think it'd be simpler just executing the `for` loop unconditionally, since there's never any differentiation between "is a leaf" and "not found".

2024-02-06 21:32 UTC, hdonnay commented on toolkit/types/csaf/csaf.go
> +package csaf
Needs doc comment.

2024-02-06 21:32 UTC, hdonnay commented on toolkit/types/csaf/csaf.go
> +type ProductList []Product
Needs doc comment.

2024-02-06 21:32 UTC, hdonnay commented on toolkit/types/csaf/csaf.go
> +type Relationships []Relationship
Needs doc comment.

2024-02-06 21:32 UTC, hdonnay commented on toolkit/types/csaf/csaf.go
> +func (pl *ProductList) Add(p Product) {
What happens when I add two `Product`s with `ID == ""`? Doesn't `ID` always have to be set?

2024-02-06 21:32 UTC, hdonnay commented on toolkit/types/csaf/csaf.go
> +type Note struct {
Needs doc comment.

2024-02-06 21:32 UTC, hdonnay commented on toolkit/types/csaf/csaf.go
> +	// TODO (crozzy): Add CVSSV4 for completeness.
```suggestion
```

2024-02-06 21:32 UTC, hdonnay commented on toolkit/types/csaf/csaf.go
> +	// Currently only CVSS v3 is supported.
```suggestion
```

2024-02-06 21:32 UTC, hdonnay commented on toolkit/types/csaf/csaf.go
> +	//
???

2024-02-07 18:04 UTC, crozzy commented on toolkit/types/csaf/csaf_test.go
> +package csaf
I think this makes a lot more sense now

2024-02-07 19:12 UTC, crozzy commented on toolkit/types/csaf/csaf.go
> +func (branch *ProductBranch) FindProductIdentifier(helperType, helperValue string) *Product {
https://docs.oasis-open.org/csaf/csaf/v2.0/os/csaf-v2.0-os.html#3133-full-product-name-type---product-identification-helper - I updated the comment.

2024-02-07 19:16 UTC, crozzy commented
There were a couple of methods that were leftovers from the go-vex implementation that are unused (and tbh I don't see when they would be used) that I removed. A few of your comments were related to those methods, I have resolved them as they don't exist anymore.

2024-02-16 16:33 UTC, crozzy commented
@hdonnay I think this is ready for another round when you have the time

2024-02-22 23:54 UTC, hdonnay approved these changes
LGTM

2024-03-18 20:12 UTC, crozzy commented
/fast-forward

2024-03-18 20:12 UTC, merged