chore: align go version with docs
quay/claircore pull request #1417
Opened 2024-09-19 15:01 UTC by crozzy

Updating to go1.22.7 which is/was the latest patch is not in-line with our own documentation https://github.com/crozzy/claircore/blob/main/docs/contributor/go_version.md.

2024-09-19 15:18 UTC, RTann approved these changes

2024-09-19 18:10 UTC, crozzy commented
Also removing `go` directive parsing as it will be the same as `oldstable`

2024-09-19 18:27 UTC, hdonnay approved these changes

2024-09-19 18:38 UTC, hdonnay requested changes

2024-09-19 18:38 UTC, hdonnay commented on .github/workflows/main.yml
>      needs: current-go-version
This needs to get removed.

2024-09-19 21:21 UTC, RTann approved these changes

2024-09-20 17:00 UTC, hdonnay approved these changes

2024-09-20 17:02 UTC, crozzy commented
/fast-forward

2024-09-20 18:10 UTC, merged