libvulnhttp: add DisableBackgroundUpdates config option
quay/claircore pull request #283
Opened 2020-12-14 16:30 UTC by jan-zmeskal

This option is useful when you develop `libvuln` library, want to keep it running but don't want regular updates to get in your way.

Signed-off-by: Jan Zmeskal <jzmeskal@redhat.com>

2020-12-15 16:53 UTC, ldelossa requested changes
I believe this is redundant. 

If you provide a empty array to UpdaterSet configuration, it instructs libvuln to not run any updater. UpdaterSet config param is a tristate: nil - use defaults, len(0) array - run no updaters, len(>0) - run only updaters provided. 

Please correct me if I'm wrong.

2020-12-16 07:53 UTC, jan-zmeskal commented
@ldelossa That is correct. However with this PR I consider scenario where you don't have config file parsing capabilities provided by `clair` CLI command. This is used when you run `cmd/libvulnhttp/main.go` directly. 

What you say could also be applied for example to [Run option](https://github.com/quay/claircore/blob/master/cmd/libvulnhttp/main.go#L25). You could achieve the same by specifying `UpdaterSet`, but when running `libvulnhttp` directly, you don't have those capabilities.

2021-01-04 17:46 UTC, ldelossa commented
@jan-zmeskal possible to accomplish this without a new config value?

2021-01-05 08:54 UTC, jan-zmeskal commented
@ldelossa I mean I can always change the code directly for example [here](https://github.com/quay/claircore/blob/f639452bfe3872d730e11462e117f122a5fcde7a/cmd/libvulnhttp/main.go#L94) when I'm developing. It just isn't the best experience. Also I though that not wanting regular updates when running `libvulnhttp` might be a legit option. However, if we want to stay clear of introducing new config options for this binary, we can close this PR and I'll just work this around by changing the code.

One other possibility is letting the user set `UpdateInterval` as env variable and changing how `UpdateInterval == 0` is treated [here](https://github.com/quay/claircore/blob/master/libvuln/opts.go#L122). However that seems like an even bigger intervention and does not solve the problem of introducing new config option to `libvulnhttp`.

Maybe there's another way, but I don't see it.

2021-01-05 14:13 UTC, ldelossa commented
Okay I see your reasoning here. Looks good to me.

2021-01-05 14:13 UTC, ldelossa approved these changes

2021-01-05 14:13 UTC, ldelossa approved these changes

2021-01-05 14:13 UTC, ldelossa commented
@jan-zmeskal needs a rebase.

2021-01-05 14:50 UTC, jan-zmeskal commented
@ldelossa done

2021-01-05 15:38 UTC, ldelossa approved these changes

2021-01-05 15:38 UTC, merged