rhel: treat vulns without FixedInVersion as unfixed
quay/claircore pull request #338
Opened 2021-03-16 12:35 UTC by jan-zmeskal

Red Hat Product Security will be enriching content of OVAL streams. Soon they'll also contain know vulnerabilities without published fix. This change enables us to treat vulnerabilities that don't have `FixedInVersion` field as unfixed.

2021-03-16 14:45 UTC, ldelossa requested changes
is there a way to provide a test to confirm this specific functionality you're fixing works?

2021-03-16 14:56 UTC, jan-zmeskal commented
@ldelossa Sure, I'll definitely provide some unit test. This is not ready for merge yet, I'm just leaving it here as a draft so that I can reference it in tickets. Thank you for pointing this out.

2021-03-18 08:24 UTC, jan-zmeskal commented
@ldelossa @hdonnay Can you please review without merging just yet? I'd like to get your opinion on the code and if you like it, I'll take it for a ride in pre-prod environment.

2021-03-18 10:48 UTC, ldelossa commented
LGTM, id personally take the approach you did her, updating the vulnVer var instead of the package version.

2021-03-19 15:24 UTC, jan-zmeskal commented
@ldelossa Feel free to merge if no further changes are required

2021-03-19 15:46 UTC, ldelossa submitted a review, later dismissed

2021-03-19 15:46 UTC, ldelossa commented
@jan-zmeskal needs rebase.

2021-03-19 17:34 UTC, ldelossa approved these changes

2021-03-19 17:34 UTC, merged