libvuln: log the names of all the configured matchers
quay/claircore pull request #529
Opened 2021-12-02 23:27 UTC by crozzy

This logs the name of each of the matchers that the matcher
instance will use. This info on startup helps when debugging
reports.

Signed-off-by: crozzy <joseph.crosland@gmail.com>

2021-12-02 23:29 UTC, crozzy commented
Came from this: https://github.com/quay/clair/discussions/1451

Logs look like this:
```
11:22PM INF matcher created component=libvuln/New name=alpine-matcher
```

2021-12-06 21:20 UTC, hdonnay requested changes
I'd rather this be a single log print -- there's going to be a lot of lines if done like this.

2021-12-06 22:37 UTC, crozzy commented
```
10:31PM INF matchers created component=libvuln/New matchers=["crda","crda","oracle","suse","ubuntu-matcher","photon","rhel","alpine-matcher","aws-matcher","debian-matcher","python"]
```
Output looks like this, interesting on the `crda` point/

2021-12-06 23:05 UTC, crozzy commented
> crda

oh, one for each supported eco-system :thinking:

2021-12-07 15:25 UTC, hdonnay submitted a review, later dismissed

2021-12-07 15:33 UTC, hdonnay approved these changes

2021-12-07 15:44 UTC, merged