postgres: Unify all all the postgres implementation of Store
quay/claircore pull request #587
Opened 2022-03-24 17:59 UTC by crozzy

In order to implement a new backend or a noop backend it'd
be good to get all the postgres specific implementation
details in one place.

Signed-off-by: crozzy <joseph.crosland@gmail.com>

2022-03-24 18:03 UTC, crozzy commented on internal/datastore/postgres/affectedmanifest.go
> +		match, err := vulnFunc(ctx, &pr, &v)
This is an issue as either way I look at it we need to change the interface. It's fairly clean accepting a func but in theory there shouldn't be application logic here so maybe the function should be split and the caller does the filtering on their side.

2022-05-13 20:37 UTC, hdonnay requested changes

2022-05-13 20:37 UTC, hdonnay commented on docs/SUMMARY.md
> +  - [Datastore MatcherStore](./reference/matcher_store.md)
```suggestion
  - [Matcher Store](./reference/matcher_store.md)
```

2022-05-13 20:37 UTC, hdonnay commented on docs/reference/matcher_store.md
> +{{# godoc datastore.MatcherStore}}
Should this just be referred to as the "Matcher Store" in prose? "Datastore MatcherStore" makes my eye twitch.

2022-05-13 20:37 UTC, hdonnay commented on vulnerability.go
> +type CheckVulnernableFunc func(ctx context.Context, record *IndexRecord, vuln *Vulnerability) (bool, error)
Needs some documentation.

2022-05-13 22:20 UTC, crozzy commented on libindex/options.go
> +	vscnrs indexer.VersionedScanners
Shouldn't be difficult to move `vscnrs` as a private member of `Libindex` if that's what you're thinking, it doesn't really make sense there as an "option" when it's just used by `Libindex` in the internal implementation.

2022-05-13 22:41 UTC, crozzy commented on libindex/init.go
> +func InitPostgresStore(_ context.Context, pool *pgxpool.Pool, doMigration bool) (indexer.Store, error) {
In the matcher side I end up moving the migrations over to the datastore too so it makes sense to have it all here

2022-05-13 22:41 UTC, crozzy commented on libindex/init.go
> +func InitPostgresStore(_ context.Context, pool *pgxpool.Pool, doMigration bool) (indexer.Store, error) {
https://github.com/crozzy/claircore/tree/crozzy-matcher-refactor/datastore/postgres/migrations

2022-05-13 22:49 UTC, crozzy commented on libindex/init.go
> +func InitPostgresStore(_ context.Context, pool *pgxpool.Pool, doMigration bool) (indexer.Store, error) {
https://github.com/quay/claircore/commit/34a38fdce99c5d39e51a59ae44ebdb1c481e7a93 is this the change you're referring to?

2022-05-16 14:51 UTC, hdonnay commented on libindex/init.go
> +func InitPostgresStore(_ context.Context, pool *pgxpool.Pool, doMigration bool) (indexer.Store, error) {
no, looks like I made those on another branch, I'll pick them off. I'm thinking of https://github.com/quay/claircore/pull/607/commits/02f679c2a81495c69c9379ce4d8837b59a4b0a3a and https://github.com/quay/claircore/pull/607/commits/16f4abdaa8d403880dee4524a966ff0c2def6c91

2022-05-16 20:10 UTC, crozzy commented
I rebased `restructure-dev` and then rebased this branch on top so we should be pretty up to date

2022-05-17 22:53 UTC, crozzy commented on test/mock/vulnstore/generate.go
> -package mock_vulnstore
moved now, thanks :+1:

2022-05-18 15:44 UTC, hdonnay requested changes

2022-05-18 17:10 UTC, crozzy commented on datastore/postgres/init.go
> +func InitDB(ctx context.Context, connString string, applicationName string) (*pgxpool.Pool, error) {
good point, renamed file and function accordingly, scans better when called

2022-05-18 17:24 UTC, hdonnay approved these changes

2022-05-18 18:04 UTC, merged