ruby: support gemspec
quay/claircore pull request #836
Opened 2023-02-17 19:44 UTC by RTann

2023-03-09 16:21 UTC, RTann commented
I can make more tests in a bit, but I wanted to open this up for review anyway

2023-03-17 18:12 UTC, RTann commented on ruby/testdata/rails.tar
I understand this is pretty large, but I'm not sure a better way to do this. I think we should have a Quay repo we can use for test images

2023-03-17 22:01 UTC, crozzy commented on ruby/testdata/rails.tar
We could try making use of the `fetch.Layer()` functionality as we do here: https://github.com/quay/claircore/blob/main/rpm/packagescanner_test.go#L1616. We already have https://quay.io/repository/projectquay/clair-fixtures I can skopeo cp as needed and/give you access to push (if you don't have it).

2023-04-03 22:03 UTC, hdonnay requested changes
This looks pending a rewrite down to a single commit

2023-04-03 23:43 UTC, RTann commented
> This looks pending a rewrite down to a single commit

not sure I follow?

2023-04-04 14:31 UTC, hdonnay commented
oh, I suppose it would. It does skip all the commit lints though, so make sure to keep a `Signed-off-by` trailer and a properly formatted subject line.

2023-04-04 14:31 UTC, hdonnay approved these changes

2023-04-04 16:35 UTC, merged