First commit
quay/claircore pull request #856
Opened 2023-03-02 22:13 UTC by daynewlee

2023-03-03 01:16 UTC, hdonnay commented
So I think as written, this produces better results in some cases:
```
            - 		Name:    "com.google.inject",
            + 		Name:    "com.google.inject:guice",
```
but some lateral moves:
```
             + 		Name:           ":spring-aop",
```
and worse in others:
```
            + 		Name:           "Apache Software Foundation:org.apache.commons.jelly.tags.fmt",
```

* * *

Something we may not call out sufficiently in contributing docs: if you run the tests with the `integration` build tag once (e.g. `go test -tags integration github.com/quay/claircore/java/jar`) this with cache assets such that even normal runs will run the full suite of tests.

2023-03-07 17:53 UTC, hdonnay requested changes
SGTM.
I think there's a better way to write that one bit, though.

The only thing that really needs to change is the commit message.
The commit should start with `jar: ...`. "Consolidation" means nothing when reading through the git log.

2023-03-07 17:53 UTC, hdonnay commented on java/jar/jar.go
> +	}
```suggestion
	// Trim to account for empty components.
	name = strings.Trim(groupId + ":" + artifactId, ":")
```

2023-03-07 19:41 UTC, hdonnay commented
Sorry to nitpick, but the subject shouldn't start capitalized. Running a command like `git log --oneline -5` should give nice, relatively uniform lines.

2023-03-07 21:30 UTC, RTann commented
@hdonnay does this merit a version bump of the package scanner?

2023-03-07 22:51 UTC, daynewlee commented
> Oh yeah, it totally does -- it'll change the reported names on some artifacts. Good catch

So I need to update this line `func (*Scanner) Version() string { return "3" }` to 4? cc: @RTann

2023-03-07 23:00 UTC, RTann commented
> > Oh yeah, it totally does -- it'll change the reported names on some artifacts. Good catch
> 
> So I need to update this line `func (*Scanner) Version() string { return "3" }` to 4 in the **packagescanner.go**? cc: @RTann

https://youtu.be/fvtQYsckLxk?t=65

2023-03-08 16:37 UTC, hdonnay requested changes
Squash the second commit into the first and rebase :+1:

2023-03-08 19:25 UTC, merged