matcher: Use latest_vuln view in lieu of querying vuln table
quay/claircore pull request #947
Opened 2023-05-23 22:27 UTC by crozzy

This view has always existed but never been used (AFAICT). Lately it has been problematic to query all of the vuln table as some vulnerabilities associated with older update_operations we're deleted or duplicated in new update_operations.

2023-05-24 18:52 UTC, crozzy commented
The number of update_operations / updater should be bounded as long as GC is on. This has the potential to cause increased latency in vulnerability report generation for cases where GC is turned off.

2023-05-24 22:22 UTC, RTann submitted a review, later dismissed
Just for a sanity check, did you check that the unit test you added fails when we don't use `latest_vulns`?

2023-05-24 22:25 UTC, crozzy commented
> Just for a sanity check, did you check that the unit test you added fails when we don't use `latest_vulns`?

yes

2023-05-25 16:06 UTC, hdonnay requested changes
Some nits that should be easy to knock out in a rebase.

LGTM after that.

2023-05-25 16:06 UTC, hdonnay commented on datastore/postgres/querybuilder_test.go
> +
extraneous whitespace

2023-05-25 16:06 UTC, hdonnay commented on datastore/postgres/querybuilder_test.go
> +			t.Fatalf("wrong number of vulns, expected %d got %d", tc.Vulnerable, len(vulns))
order should be "got", "want"

2023-05-25 17:56 UTC, merged