indexer: Cache scanner table
quay/claircore pull request #960
Opened 2023-06-05 17:36 UTC by crozzy

During the indexing cycle many operations try to read information from the scanner table, this can occasionally lead to resource contention depending on the DB. This reads the table into memory when the indexer store is instanciated and uses when asked for scanner info.

2025-06-20 16:45 UTC, RTann commented
> [crozzy](https://github.com/crozzy) [force-pushed](https://github.com/quay/claircore/compare/8620166b9eb5e966fb32d387ad9541f8f2dde439..33f440fcc1eebad7491e988f1cf5da06828864f6) the cached-scanners branch 2 times, most recently from [8620166](https://github.com/quay/claircore/commit/8620166b9eb5e966fb32d387ad9541f8f2dde439) to [33f440f](https://github.com/quay/claircore/commit/33f440fcc1eebad7491e988f1cf5da06828864f6) 
[2 years ago](https://github.com/quay/claircore/pull/960#event-9436511767)

2 years ago???

2025-06-20 17:30 UTC, RTann reviewed
So let's say we are in the process of updating the Indexer and/or Matcher version(s) to add or delete a scanner.

Add: I think this is ok. The older versions won't even look for it (I believe)

Delete: The older versions will still claim the scanner exists, though I guess it'll still fail the next part of the scan process, maybe?

Can you add any commentary to potential race scenarios to see if we are ok with the possibilities?

2025-06-20 17:30 UTC, RTann commented on datastore/postgres/registerscanners.go
> +	s.scanners = make(map[string]int64)
This is already done in `indexer_store.go`

2025-06-20 17:30 UTC, RTann commented on datastore/postgres/registerscanners.go
> +const selectAllScanner = `
nit: `selectAllScanners`?

2025-06-20 17:30 UTC, RTann commented on datastore/postgres/registerscanners.go
> +	for rows.Next() {
I think we still need a `defer rows.Close()` (I don't think it'll close if `rows.Scan` fails) and a `rows.Err()` check, too

2025-06-20 17:30 UTC, RTann commented on datastore/postgres/indexer_store.go
> +	scanners map[string]int64
this may be a decent candidate for `map[unique.Handle[string]]int64` since I think this map will be rather static once it's initially populated

2025-06-20 17:30 UTC, RTann commented on datastore/postgres/registerscanners.go
> +	return s.populateScanners(ctx)
is it assumed that `RegisterScanners` is called only once and in the very beginning of the process?

2025-06-20 17:30 UTC, RTann commented on datastore/postgres/registerscanners.go
> +func (s *IndexerStore) populateScanners(ctx context.Context) error {
nit: `initScanners`

2026-04-24 15:06 UTC, hdonnay commented
@crozzy do we (read: you) want to update this and land it or close this PR and try from scratch?

2026-04-24 15:08 UTC, crozzy commented
Hopefully dust it off, I'll update today or create a new PR

2026-04-24 17:33 UTC, hdonnay requested changes
Needs updating

2026-04-29 01:33 UTC, hdonnay commented on datastore/postgres/indexer_store.go
> +	scanners sync.Map
It seems like this should be a `map[string]int64` and a `sync.Once`.

The use of a concurrent map makes it seem like there's an expectation that `populateScanners` can run concurrently to a `selectScanners` when it really shouldn't.

2026-04-29 16:15 UTC, crozzy commented on datastore/postgres/indexer_store.go
> +	scanners sync.Map
yeah, that's fair enough, good idea

2026-04-29 16:23 UTC, hdonnay requested changes

2026-04-29 16:23 UTC, hdonnay commented on datastore/postgres/registerscanners.go
> +}
These should try the `Once`, and so should probably also take a `context.Context`.

2026-04-29 16:54 UTC, hdonnay approved these changes
LGTM

2026-04-29 17:04 UTC, crozzy commented
/fast-forward

2026-04-29 17:04 UTC, merged